# Generated by Django 3.1.3 on 2022-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20221213_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='indicator',
            new_name='is_correct',
        ),
        migrations.AddField(
            model_name='choice',
            name='lesson',
            field=models.ManyToManyField(to='onlinecourse.Lesson'),
        ),
    ]
