# Generated by Django 3.1.3 on 2022-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20221213_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1),
        ),
    ]
