# Generated by Django 3.1.3 on 2022-12-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20221213_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.CharField(choices=[(True, True), (False, False)], max_length=9, verbose_name='Is this correct answer?'),
        ),
    ]
