# Generated by Django 3.1.3 on 2022-12-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20221213_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='choices',
            new_name='choice',
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.CharField(choices=[('True', True), ('False', False)], max_length=9, verbose_name='Is this correct answer?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Grade for all correct answers'),
        ),
    ]
