# Generated by Django 3.1.3 on 2022-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_auto_20221214_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ManyToManyField(to='onlinecourse.Question'),
        ),
    ]
